version: 3
profiles:
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 192.168.1.102
      user: cosmos
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    name: Cosmic PC - cosmos
    group: Home Network
    color: '#3030cc'
    id: ssh:custom:Cosmic-PC-cosmos:be0ff54f-c758-4b5c-ba69-1cfbadea9463
  - type: local
    options:
      env: {}
      cwd: /home/dataviking
      command: bash
      args:
        - curl
        - wttr.in/~Joppa+MD
        - '&'
    group: Utilities
    color: '#555555'
    name: Weather
    icon: fas fa-cloud-showers-heavy
    id: local:custom:Weather:e58228a3-415d-46a1-81d6-270ea3f7b07b
  - type: local
    options:
      env: {}
      cwd: /home/dataviking
      command: bash
      args:
        - /home/dataviking/dfortress
    group: Utilities
    color: '#775500'
    name: Dwarf Fortress
    icon: fas fa-dungeon
    id: local:custom:Dwarf-Fortress:9a654010-be8a-49ee-b0c8-f3aeff39d616
  - type: local
    options:
      env: {}
      cwd: /home/dataviking
      command: wtfutil
      args: []
    group: Utilities
    color: '#7733dd'
    name: dashboard
    icon: fas fa-newspaper
    id: local:custom:dashboard:9132ca46-fe5e-440a-971e-60d4c72d3f47
  - type: ssh
    options:
      host: 192.168.1.118
      user: dataviking
      algorithms: {}
    weight: -1
    name: penguin
    group: Home Network
    icon: fas fa-laptop-code
    color: '#00aa00'
    id: ssh:custom:penguin:edb10f81-ab82-44d9-b62c-d71bf8662f8e
  - type: local
    options:
      command: /usr/bin/xonsh
      args:
        - '-l'
      env: {}
      cwd: /home/dataviking
    icon: fab fa-python
    color: '#ffd343'
    id: local:custom:Xonsh-Home:3829976e-7327-4d74-bd53-86258c2fa53d
    group: Shells
    name: xonsh
  - type: local
    options:
      command: /bin/bash
      args:
        - '--login'
      env: {}
      cwd: /home/dataviking
    id: local:custom:User-default:187a2eb8-6a03-4997-8be6-57d7fd98cb41
    name: bash
    group: Shells
    icon: fas fa-terminal
    color: '#994400'
  - type: ssh
    name: thedarkwower
    icon: fas fa-desktop
    options:
      host: 192.168.1.128
      user: dataviking
      algorithms:
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      auth: password
      scripts:
        - expect: ''
          send: xonsh
      privateKeys: []
      forwardedPorts: []
    weight: -1
    group: Home Network
    color: '#7733dd'
    id: ssh:custom:thedarkwower:dda31386-660c-4d2e-9eba-674841a54a61
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 192.168.1.102
      user: dataviking
      algorithms: {}
    weight: -1
    name: Cosmic PC - dataviking
    id: ssh:custom:Cosmos:a7900796-fe5c-42c0-a0a0-b8d3d7b37860
    group: Home Network
    color: '#3030cc'
  - type: ssh
    name: homelab
    icon: fas fa-server
    options:
      host: 192.168.1.132
      user: dataviking
      algorithms:
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
    weight: -1
    color: '#c51a4a'
    id: ssh:custom:homelab:51279b84-0f0c-4ccf-afa3-8afb209b293c
    group: Home Network
hotkeys:
  toggle-window: []
  ctrl-c:
    - - Ctrl-C
  copy: []
  paste:
    - - Ctrl-V
  select-all:
    - Ctrl-Shift-A
  clear:
    - - Ctrl-Space
  zoom-in:
    - - Ctrl-=
  zoom-out:
    - - Ctrl--
  reset-zoom:
    - - Ctrl-0
  home:
    - - Home
  end:
    - - End
  previous-word:
    - - Ctrl-Left
  next-word:
    - - Ctrl-Right
  delete-previous-word: []
  delete-next-word: []
  search:
    - - Ctrl-F
  pane-focus-all:
    - - Ctrl-B
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings:
    - - Ctrl-Escape
  serial: []
  restart-serial-session: []
  new-window: []
  new-tab:
    - - Ctrl-N
  profile: {}
  profile-selectors:
    split-layout:
      - - Super-Shift-L
  toggle-fullscreen: []
  close-tab: []
  reopen-tab: []
  toggle-last-tab: []
  rename-tab: []
  next-tab: []
  previous-tab: []
  move-tab-left: []
  move-tab-right: []
  rearrange-panes:
    - - Alt-P
  tab-1:
    - - Ctrl-1
  tab-2:
    - - Ctrl-2
  tab-3:
    - - Ctrl-3
  tab-4:
    - - Ctrl-4
  tab-5:
    - - Ctrl-5
  tab-6:
    - - Ctrl-6
  tab-7:
    - - Ctrl-7
  tab-8:
    - - Ctrl-8
  tab-9:
    - - Ctrl-9
  tab-10:
    - - Ctrl-0
  tab-11:
    - - Ctrl-Alt-1
  tab-12:
    - - Ctrl-Alt-2
  tab-13:
    - - Ctrl-Alt-3
  tab-14:
    - - Ctrl-Alt-4
  tab-15:
    - - Ctrl-Alt-5
  tab-16:
    - - Ctrl-Alt-6
  tab-17:
    - - Ctrl-Alt-7
  tab-18:
    - - Ctrl-Alt-8
  tab-19:
    - - Ctrl-Alt-9
  tab-20:
    - - Ctrl-Alt-0
  split-right:
    - - Ctrl-Shift-Right
  split-bottom:
    - - Ctrl-Shift-Down
  split-left:
    - - Ctrl-Shift-Left
  split-top:
    - - Ctrl-Shift-Up
  pane-nav-right: []
  pane-nav-down: []
  pane-nav-up: []
  pane-nav-left: []
  pane-nav-previous: []
  pane-nav-next: []
  pane-maximize: []
  switch-profile: []
  profile-selector:
    - - Ctrl-M
  close-pane:
    - - Ctrl-Shift-Escape
  scroll-to-bottom: []
  settings-tab: {}
  explode-tab:
    - Ctrl-Shift-.
  combine-tabs:
    - Ctrl-Shift-,
  duplicate-tab: []
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  copy-current-path: []
terminal:
  searchOptions: {}
  colorScheme:
    name: Dracula
    foreground: '#f8f8f2'
    background: '#1e1f29'
    cursor: '#bbbbbb'
    colors:
      - '#000000'
      - '#ff5555'
      - '#bd93f9'
      - '#f1fa8c'
      - '#bd93f9'
      - '#ff79c6'
      - '#8be9fd'
      - '#bbbbbb'
      - '#555555'
      - '#ff5555'
      - '#bd93f9'
      - '#f1fa8c'
      - '#bd93f9'
      - '#ff79c6'
      - '#8be9fd'
      - '#ffffff'
  customColorSchemes:
    - name: Cool
      foreground: '#6600aa'
      background: '#000000'
      cursor: '#777777'
      colors:
        - '#000000'
        - '#004499'
        - '#00cc00'
        - '#004499'
        - '#00cc00'
        - '#004499'
        - '#004499'
        - '#bfbfbf'
        - '#666666'
        - '#004499'
        - '#00cc00'
        - '#e5e5e5'
        - '#004499'
        - '#004499'
        - '#00e5e5'
        - '#e5e5e5'
    - name: Dracula
      foreground: '#f8f8f2'
      background: '#1e1f29'
      cursor: '#bbbbbb'
      colors:
        - '#000000'
        - '#ff5555'
        - '#bd93f9'
        - '#f1fa8c'
        - '#bd93f9'
        - '#ff79c6'
        - '#8be9fd'
        - '#bbbbbb'
        - '#555555'
        - '#ff5555'
        - '#bd93f9'
        - '#f1fa8c'
        - '#bd93f9'
        - '#ff79c6'
        - '#8be9fd'
        - '#ffffff'
    - name: FirefoxDev
      foreground: '#7c8fa4'
      background: '#0e1011'
      cursor: '#708284'
      colors:
        - '#002831'
        - '#e63853'
        - '#5eb83c'
        - '#a57706'
        - '#359ddf'
        - '#d75cff'
        - '#4b73a2'
        - '#dcdcdc'
        - '#001e27'
        - '#e1003f'
        - '#1d9000'
        - '#cd9409'
        - '#006fc0'
        - '#a200da'
        - '#005794'
        - '#e2e2e2'
  background: colorScheme
  hideTabIndex: true
  profile: local:custom:Xonsh-Home:3829976e-7327-4d74-bd53-86258c2fa53d
  showBuiltinProfiles: false
  showTabProfileIcon: true
  ligatures: true
  font: Hack
ssh:
  knownHosts:
    - host: 192.168.1.132
      port: 22
      type: ecdsa-sha2-nistp256
      digest: vZFwPX2hBKZs5enwXJVGt4Ugh5CBlj48oczLUHVG5To=
    - host: 192.168.1.102
      port: 22
      type: ecdsa-sha2-nistp256
      digest: UofWgBtcAf681hrkc/FY/ic+mAF68IXfp0ZG4y5TzDo=
    - host: 192.168.1.146
      port: 22
      type: ecdsa-sha2-nistp256
      digest: NLAixKSjlPoIaSqAziL/DNZePhhAehSCFXtsZFX0LkA=
    - host: 192.168.1.128
      port: 22
      type: ecdsa-sha2-nistp256
      digest: OIZx4b0CHJT/1gdQgdhTV6zebVgi63UCPKVXOqUuris=
clickableLinks: {}
appearance:
  vibrancy: true
pluginBlacklist: []
enableWelcomeTab: false
profileDefaults: {}
electronFlags:
  - - force_discrete_gpu
    - '0'
hacks: {}
accessibility: {}
configSync:
  parts: {}
  token: >-
    1af2e626ddd0411ebb8e000a1369bbc8ca92da7c01d410a73ca871796b89a83be1b1d99705a27ee6761e4cd77118b4fda34d42ebff9fc9e347a6dc523685a18d
  configID: 7242
  auto: true
