# 24 bit color
set-option -sa terminal-overrides ",screen-256color:Tc"

# Unbind default Ctrl + b
unbind C-b

# Set prefix to Ctrl + a
set-option -g prefix C-a
bind C-a send-prefix

# Better usability
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on
set -g history-limit 10000
set -g set-clipboard on
set-option -g allow-rename on

# Easier switching between windows
bind -n C-Left  previous-window
bind -n C-Right next-window

# Make split directions more intuitive
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}" 
unbind '"'
unbind %
unbind n
bind n new-window
unbind q
bind q kill-window

# Reload tmux config easily
bind r source-file ~/.config/tmux/tmux.conf

# Status bar styling (optional, clean)
set -g status-position top
set -g status-bg '#000000'
set -g status-fg white

set -g status-left ''
set -g status-left-length 10

set -g status-right "#[fg=#8839ef]%H:%M"

setw -g window-status-current-style 'fg=#000000 bg=#8839ef'
setw -g window-status-current-format '#[fg=#8839ef bg=#000000]#[fg=#000000 bg=#8839ef]#I #W #[fg=#8839ef bg=#000000]'

setw -g window-status-style 'fg=#8839ef bg=#000000'
setw -g window-status-format ' #[fg=white]#I #[fg=white]#W '
