# menu
set $menu wofi --show drun
bindsym $mod+Space exec $menu

# 1 -  terminal / file manager 
set $term kitty
bindsym $mod+Return workspace 1, exec $term
#assign [app_id="kitty"] 1

set $files thunar
bindsym $mod+t exec $files, workspace 1
assign [app_id="thunar"] 1

# 2 -  mpv & cava
set $music $HOME/.config/scripts/music_selector.sh
bindsym $mod+j exec $music, workspace 2
assign [app_id="mpv"] 2
assign [title="cava"] 2

# 3 - 󰖟 browser 
set $browser brave --ozone-platform=wayland
bindsym $mod+b exec $browser, workspace 3
assign [app_id="brave-browser"] 3

# 4 - 󰭹 signal 
set $sms signal-desktop
bindsym $mod+s exec $sms, workspace 4
assign [app_id="signal-desktop"] 4

# 5 -  game engine 
set $engine godot
bindsym $mod+g exec $engine , workspace 5
assign [app_id="org.godotengine.ProjectManager"] 5

# 6 -  script editor
assign [title="Script Editor - Godot Engine"] 6

# 6 -  code editor
set $code codium --ozone-platform=wayland
bindsym $mod+c exec $code, workspace 6
assign [app_id="codium"] 6

# 6 - micro
set $plaintext kitty -e micro
bindsym $mod+m exec $plaintext, workspace 6
assign [title="micro"] 6

# 6 - neovim
set $nvim kitty -e nvim
bindsym $mod+n $nvim, workspace 6
assign [title="neovim"] 6

# 7 -  krita
set $graphics krita
bindsym $mod+k exec $graphics, workspace 7
assign [app_id="krita"] 7

# 8 - 󰛓 writer
set $writer focuswriter
bindsym $mod+f exec $writer, workspace 8
assign [app_id="focuswriter"] 8

# 9 -  - gsw
set $gsw kitty -e gsw -r $(wofi --dmenu --prompt "repo directory:")
bindsym $mod+w exec $gsw, workspace 9
assign [title="gsw"] 9

# 10 - 󰊗 steam and dwarf fortress
set $df kitty -e dwarffortress
bindsym $mod+d exec $df, workspace 10
assign [app_id="kitty" title="dwarffortress"] 10

set $steam steam
bindsym $mod+v exec $steam, workspace 10
assign [title="Steam"] 10

# other window rules
for_window [window_type="dialog"] floating enable
for_window [window_role="pop-up"] floating enable
for_window [app_id="pavucontrol"] floating enable
for_window [app_id="kitty" title="nmtui"] floating enable
