### Output configuration
#
# wallpaper handled in eyecandy.conf

output HDMI-A-2 resolution 1920x1080 position 0,0
output eDP-1 resolution 1366x768 position 1920,0

set $laptop eDP-1
bindswitch --reload --locked lid:on output $laptop disable
bindswitch --reload --locked lid:off output $laptop enable